### ISSUE TITLE
Enhancement: support openapi 3.0.0

### ISSUE THREAD

**Issue by suihanki** [globality-corp/openapi#4]
Hi folks! This tool has been super helpful in starting to build out the first version of our Open API spec. Wondering if anyone is thinking about supporting the 3.0.0 schema?

**Comment by jessemyers** [comment]
It hasn't been a priority for us, but we'd definitely consider PRs in that direction.

For reference, our main use case for this library to generate API definitions from our application code. Our [microcosm-flask](https://github.com/globality-corp/microcosm-flask) library allows us to define CRUD (and other) web services using strong conventions to generate Open API definitions that match our Python code. (That is, write your code, generate your Open API). We then automate client code using Yelp's [bravado](https://github.com/Yelp/bravado) library.

This has been very nice in practice.

re: Open API 3, I've only looked briefly, but I didn't see anything in the change set that we couldn't live without, so we haven't prioritized moving forward.

**Comment by suihanki** [comment]
Thanks @jessemyers - that's exactly what I'm starting to do with this library, it's worked quite well! The change of generating API code from a spec instead is just too much for us to consider now... I was just hoping that with this being our first attempt at releasing a spec, we could start with a later version. At the same time though, the toolset/ecosystem around v3 seems much more limited... so not a whole lot lost at this point. Thanks for the reply!

**Comment by jessemyers** [comment]
No problem. Please happy to provider more guidance if you're interested in leveraging our `microcosm-flask` tooling. It's working well for us.
