### ISSUE TITLE
Update package python version?

### ISSUE THREAD

**Issue by suihanki** [globality-corp/openapi#6]
Hi again!

Noticed you did some work recently to get rid of "python2-isms" :) any chance we could update the package python version to indicate that it supports python 3? We've added some new tests recently to prevent packages that aren't py3~ ready, we're using this package to check:

https://github.com/brettcannon/caniusepython3/

Basically just looks for anything that starts with "Programming Language :: Python :: 3" in the package classifiers, like this package here:

https://pypi.python.org/pypi/opencv-python/json/

Thanks very much!
Brendan

**Comment by suihanki** [comment]
fwiw - it would just be an update like this, happy to submit a PR with the change if you think it makes sense!

`setup(
    name=project,
    version=version,
    description="Python OpenAPI 2.0 (Swagger) object model",
    author="Globality Engineering",
    author_email="engineering@globality.com",
    url="https://github.com/globality-corp/openapi",
    packages=find_packages(exclude=["*.tests", "*.tests.*", "tests.*", "tests"]),
    include_package_data=True,
    zip_safe=False,
    keywords="openapi swagger",
    classifiers=[
        "Programming Language :: Python :: 3"
    ],
    install_requires=[
        "inflection>=0.3.1",
        "jsonschema>=2.6.0",
    ],
    extras_require={
        "yaml": [
            "PyYAML>=3.12",
        ],
    },
    setup_requires=[
        "nose>=1.3.6",
    ],
    dependency_links=[
    ],
    entry_points={
    },
    tests_require=[
        "coverage>=3.7.1",
        "mock>=1.0.1",
        "PyHamcrest>=1.8.5",
    ],
)`

**Comment by jessemyers** [comment]
A PR would be lovely.

**Comment by suihanki** [comment]
#7 added!

**Comment by suihanki** [comment]
Thanks @jessemyers I believe we'd need to cut a new release as well? Thanks for the help thus far.

**Comment by jessemyers** [comment]
Done. https://pypi.python.org/pypi/openapi

**Comment by suihanki** [comment]
Woohoo! Thanks @jessemyers
